package com.sbm.mc.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class RvpApilodgingAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRvpApilodgingAllPropertiesEquals(RvpApilodging expected, RvpApilodging actual) {
        assertRvpApilodgingAutoGeneratedPropertiesEquals(expected, actual);
        assertRvpApilodgingAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRvpApilodgingAllUpdatablePropertiesEquals(RvpApilodging expected, RvpApilodging actual) {
        assertRvpApilodgingUpdatableFieldsEquals(expected, actual);
        assertRvpApilodgingUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRvpApilodgingAutoGeneratedPropertiesEquals(RvpApilodging expected, RvpApilodging actual) {
        assertThat(expected)
            .as("Verify RvpApilodging auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRvpApilodgingUpdatableFieldsEquals(RvpApilodging expected, RvpApilodging actual) {
        assertThat(expected)
            .as("Verify RvpApilodging relevant properties")
            .satisfies(e -> assertThat(e.getName()).as("check name").isEqualTo(actual.getName()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRvpApilodgingUpdatableRelationshipsEquals(RvpApilodging expected, RvpApilodging actual) {}
}
